import Head from 'next/head'
import Navbar from '../components/Navbar'
import About from '../components/About'
import Menu from '../components/Menu'
import Contact from '../components/Contact'
import Footer from '../components/Footer'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
        <Navbar/>
        <About/>
        <Menu/>
        <Contact/>
    </div>
  )
}
